name: Generate update.json on release

on:
  release:
    types: [published]

jobs:
  gen_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # нужно, чтобы пушить файл

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release info
        id: rel
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.payload.release.tag_name || ''
            return { tag }

      - name: Download APK asset from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG=${{ steps.rel.outputs.tag }}
          echo "Tag: $TAG"
          # Получаем список assets и находим apk
          ASSET_URL=$(jq -r '.assets[] | select(.name | test("\\.apk$")) | .browser_download_url' <<< "${{ toJson(github.event.release) }}")
          if [ -z "$ASSET_URL" ]; then
            echo "No APK asset found in release"
            exit 1
          fi
          echo "Asset URL: $ASSET_URL"
          curl -L -o release.apk "$ASSET_URL"

      - name: Compute sha256
        run: |
          SHA=$(sha256sum release.apk | awk '{print $1}')
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      - name: Prepare update.json
        run: |
          TAG=${{ steps.rel.outputs.tag }}
          VNAME=${TAG#v}
          VCODE=$(date +%s)  # fallback: timestamp as versionCode; можно заменить на своё правило
          APK_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/$(ls release.apk)"
          cat > docs/update.json <<EOF
{
  "versionCode": ${VCODE},
  "versionName": "${VNAME}",
  "notes": "${{ github.event.release.body | jq -sR . }}",
  "apkUrl": "${APK_URL}",
  "sha256": "${{ steps.gen_update.outputs.sha256 }}",
  "minSdk": 28
}
EOF

      - name: Commit and push update.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/update.json
          git commit -m "Update update.json for ${TAG}" || echo "no changes to commit"
          git push origin HEAD:main
